// The Table: boot, header controls, hash router. No build step; vanilla ES modules.
import { getToken, get, patch, post, setSignedOutHandler, setToken } from './api.js';
import { h, icon } from './dom.js';
import { openHowto } from './howto.js';
import { currentLang, guessLang, setLang, t } from './i18n.js';
import { state, loading, errorBox, go } from './ui.js';
import { joinView, loginView, rememberJoinToken } from './views/auth.js';
import { adminView } from './views/admin.js';
import { bookView, chapterView } from './views/book.js';
import { filmsView } from './views/films.js';
import { meView } from './views/me.js';
import { scoreView } from './views/score.js';
import { newThreadView, shelfView, tableView, threadView } from './views/table.js';

const SCALES = { 1: 1, 2: 1.15, 3: 1.32, 4: 1.55 };
const view = document.getElementById('view');
let routeSeq = 0;

async function ensureConfig() {
  // Production: /family/config.js (generated by site/build.py) sets window.EAI.
  // Local dev: family/app/config.dev.js (see that file), loaded only on localhost.
  if (!window.EAI && ['localhost', '127.0.0.1'].includes(location.hostname)) {
    try { await import('../config.dev.js'); } catch { /* none */ }
  }
  window.EAI = window.EAI || { apiBase: '', howto: null };
}

function applySize(n) {
  n = SCALES[n] ? n : 1;
  document.documentElement.style.setProperty('--eai-text-scale', String(SCALES[n]));
  document.documentElement.dataset.textSize = String(n);
  try { localStorage.setItem('eai.text_size', String(n)); } catch { /* ignore */ }
  document.querySelectorAll('#size-pop button').forEach((b) => b.setAttribute('aria-pressed', String(Number(b.dataset.size) === n)));
}

function savedSize() {
  try { return Number(localStorage.getItem('eai.text_size')) || 1; } catch { return 1; }
}

const actions = {
  async setLang(l) {
    await setLang(l);
    markLang();
    if (state.me) {
      state.me.lang = l;
      patch('/api/me', { lang: l }).catch(() => {});
    }
    route();
  },
  async setSize(n) {
    applySize(n);
    if (state.me) {
      state.me.text_size = n;
      patch('/api/me', { text_size: n }).catch(() => {});
    }
    if ((location.hash || '').startsWith('#/me')) route();
  },
  swapToken(tok) { if (tok) setToken(tok); },
  async logout() {
    try { await post('/api/logout'); } catch { /* already gone */ }
    setToken(null);
    state.me = null;
    state.shelves = null;
    go('#/login');
  },
};

function markLang() {
  document.querySelectorAll('.lang-toggle [data-lang]').forEach((b) => {
    const on = b.dataset.lang === currentLang();
    b.classList.toggle('on', on);
    b.setAttribute('aria-pressed', String(on));
  });
}

function setupChrome() {
  document.querySelectorAll('[data-icon]').forEach((el) => el.append(icon(el.dataset.icon)));
  document.querySelectorAll('.lang-toggle [data-lang]').forEach((b) => b.addEventListener('click', () => actions.setLang(b.dataset.lang)));
  const pop = document.getElementById('size-pop');
  const btn = document.getElementById('size-btn');
  for (const n of [1, 2, 3, 4]) {
    pop.append(h('button', { type: 'button', class: 'size-opt size-' + n, 'data-size': n, 'aria-label': t('family.me.size_n', { n }), onclick: () => { actions.setSize(n); pop.hidden = true; btn.setAttribute('aria-expanded', 'false'); } }, 'A'));
  }
  btn.addEventListener('click', () => {
    pop.hidden = !pop.hidden;
    btn.setAttribute('aria-expanded', String(!pop.hidden));
    if (!pop.hidden) pop.querySelector('[aria-pressed=true]')?.focus();
  });
  document.addEventListener('click', (ev) => {
    if (!pop.hidden && !pop.contains(ev.target) && !btn.contains(ev.target)) { pop.hidden = true; btn.setAttribute('aria-expanded', 'false'); }
  });
  document.getElementById('help-btn').addEventListener('click', () => openHowto({ autoplay: true }));
  setSignedOutHandler(() => { state.me = null; go('#/login'); });
  window.addEventListener('hashchange', route);
  state.rerender = route;
}

async function signedIn(member) {
  state.me = await get('/api/me').catch(() => member);
  if (state.me.lang && state.me.lang !== currentLang()) await setLang(state.me.lang); // the server's choice wins
  markLang();
  applySize(state.me.text_size || 1);
  go('#/');
  if (!state.me.seen_howto) {
    openHowto({ autoplay: true, onClose: () => { state.me.seen_howto = true; patch('/api/me', { seen_howto: true }).catch(() => {}); } });
  }
}

function markNav(name) {
  document.querySelectorAll('.tabs a').forEach((a) => {
    if (a.dataset.route === name) a.setAttribute('aria-current', 'page');
    else a.removeAttribute('aria-current');
  });
  document.querySelectorAll('.admin-only').forEach((el) => { el.hidden = !(state.me && state.me.role === 'admin'); });
  document.body.dataset.authed = state.me ? 'yes' : 'no';
}

async function route() {
  const seq = ++routeSeq;
  const parts = (location.hash.replace(/^#\/?/, '') || '').split('/').filter(Boolean);
  const [a, b] = parts;
  if (a === 'join' && b) {
    rememberJoinToken(decodeURIComponent(b));
    history.replaceState(null, '', location.pathname + location.search + '#/join'); // keep the token out of history
  }
  const isPublic = a === 'join' || a === 'login';
  if (!state.me && getToken() && a !== 'join') {
    try {
      state.me = await get('/api/me');
      if (state.me.lang !== currentLang()) await setLang(state.me.lang);
      markLang();
      applySize(state.me.text_size);
    } catch (e) {
      if (!getToken()) return; // signed out by the 401 handler, which already went to #/login
      if (!isPublic) { view.replaceChildren(errorBox(e, route)); return; }
    }
  }
  if (!isPublic && !state.me) { go('#/login'); return; }
  if (a === 'login' && state.me) { go('#/'); return; }
  document.body.classList.remove('games-tv'); // the TV screen re-adds it; leaving it must restore the chrome
  document.body.classList.remove('games-play');
  markNav(isPublic ? '' : (a || 'table') === 't' || a === 'shelf' || a === 'new' ? 'table' : (a || 'table'));
  view.replaceChildren(loading());
  let node;
  try {
    switch (a) {
      case undefined: node = await tableView(); break;
      case 'join': node = await joinView(signedIn); break;
      case 'login': node = await loginView(signedIn); break;
      case 't': node = await threadView(b); break;
      case 'shelf': node = await shelfView(b); break;
      case 'new': node = await newThreadView(b); break;
      case 'book': node = b ? await chapterView(b) : await bookView(); break;
      case 'films': node = await filmsView(); break;
      case 'games': node = await (await import('./games/index.js')).gamesView(parts.slice(1)); break;
      case 'score': node = await scoreView(b); break;
      case 'admin': node = state.me.role === 'admin' ? await adminView() : errorBox({ key: 'family.errors.forbidden' }); break;
      case 'me': node = await meView(actions); break;
      default: node = errorBox({ key: 'family.errors.not_found' });
    }
  } catch (e) {
    node = errorBox(e, route);
  }
  if (seq !== routeSeq) return;
  view.replaceChildren(node);
  if (a !== 't') window.scrollTo(0, 0);
  const h1 = view.querySelector('h1');
  document.title = (h1 ? h1.textContent + ' · ' : '') + t('family.app.title');
}

async function boot() {
  await ensureConfig();
  applySize(savedSize());
  await setLang(guessLang());
  setupChrome();
  markLang();
  await route();
}

boot();
