// Dots & Lines: the pieces, drawn in code as SVG (no images, no innerHTML) in W5's look (contracts/games-art.md):
// fat enamel pieces whose silhouette is the suit, so the shape reads before the colour does.
//   Coral ● disc · Sky ■ rounded tile · Leaf ▲ rounded triangle · Plum ◆ rounded diamond · Spark ✦ cream disc
// The geometry below is a copy of family/app/games-assets/dots.json (generated by tools/games_assets.py);
// applyArt(json) swaps in the live file, so a regenerated art set needs no change here.
// Classes are W5's (.gm-dot .gm-dot--{r,b,g,p,s}, .gm-dot--as + .gm-as) so games-theme.css styles every state.
import { t } from '../i18n.js';

const NS = 'http://www.w3.org/2000/svg';

let ART = {
  plate: '#10201a',
  shadowDy: 8,
  sideDy: 5,
  suits: {
    r: { color: '#ff9478', side: '#735141', path: 'M50 3a43 43 0 1 1-0.01 0Z', round: 0, gloss: 'M20 30A36 36 0 0 1 40 12', number: { x: 50, y: 62, size: 50, size2: 44 } },
    b: { color: '#7fd0ff', side: '#3d6a7a', path: 'M27 8h46a19 19 0 0 1 19 19v42a19 19 0 0 1-19 19h-46a19 19 0 0 1-19-19v-42a19 19 0 0 1 19-19Z', round: 0, gloss: 'M17 32V27a10 10 0 0 1 10-10h12', number: { x: 50, y: 63, size: 52, size2: 46 } },
    g: { color: '#8fdc5c', side: '#447035', path: 'M50 12L89 82H11Z', round: 13, gloss: 'M37 36L45 22', number: { x: 50, y: 77, size: 46, size2: 38 } },
    p: { color: '#b98cf5', side: '#554e75', path: 'M50 9L89 47L50 85L11 47Z', round: 12, gloss: 'M22 41L36 27', number: { x: 50, y: 63, size: 48, size2: 40 } },
  },
  spark: {
    color: '#f4efe3', side: '#6e786e', path: 'M50 3a43 43 0 1 1-0.01 0Z', star: '#ff7a3d',
    starPath: 'M50 13C53.4 35 59 41 81 46C59 51 53.4 57 50 79C46.6 57 41 51 19 46C41 41 46.6 35 50 13Z',
    core: 'M50 31C51.2 40 53 43 61 46C53 49 51.2 52 50 61C48.8 52 47 49 39 46C47 43 48.8 40 50 31Z',
  },
};

const PATH_OK = /^[MLHVCSQTAZmlhvcsqtaz0-9 .,\-]+$/;
const COLOR_OK = /^#[0-9a-f]{6}$/i;

// Take W5's dots.json if it loaded (index.js or play.js fetches it once). Anything malformed is ignored.
export function applyArt(spec) {
  if (!spec || typeof spec !== 'object') return;
  try {
    for (const s of spec.suits || []) {
      const cur = ART.suits[s.key];
      if (!cur || !PATH_OK.test(s.path) || !COLOR_OK.test(s.color) || !COLOR_OK.test(s.side)) continue;
      ART.suits[s.key] = {
        color: s.color, side: s.side, path: s.path, round: Number(s.round_stroke) || 0,
        gloss: PATH_OK.test(s.gloss || '') ? s.gloss : '',
        number: { x: +s.number.x, y: +s.number.y, size: +s.number.size, size2: +s.number.size_two_digits },
      };
    }
    const sp = spec.spark;
    if (sp && PATH_OK.test(sp.path) && PATH_OK.test(sp.star_path) && COLOR_OK.test(sp.color) && COLOR_OK.test(sp.star)) {
      ART.spark = { ...ART.spark, color: sp.color, path: sp.path, star: sp.star, starPath: sp.star_path };
    }
    if (spec.token) {
      if (Number.isFinite(+spec.token.shadow_dy)) ART.shadowDy = +spec.token.shadow_dy;
      if (Number.isFinite(+spec.token.side_dy)) ART.sideDy = +spec.token.side_dy;
      if (COLOR_OK.test(spec.token.number_fill || '')) ART.plate = spec.token.number_fill;
    }
  } catch { /* keep the built-in art */ }
}

function el(tag, attrs) {
  const n = document.createElementNS(NS, tag);
  for (const [k, v] of Object.entries(attrs || {})) n.setAttribute(k, String(v));
  return n;
}

function svg() {
  return el('svg', { viewBox: '0 0 100 100', 'aria-hidden': 'true', focusable: 'false' });
}

// shadow, side, face, rim, gloss: the enamel piece, layer by layer (the same stack as dots.svg#gm-token-*).
function body(s, d, round, color, side) {
  const stroke = (c) => (round ? { stroke: c, 'stroke-width': round, 'stroke-linejoin': 'round' } : {});
  s.append(el('path', { d, fill: '#000', ...stroke('#000'), transform: `translate(0 ${ART.shadowDy})`, opacity: '.3' }));
  s.append(el('path', { d, fill: side, ...stroke(side), transform: `translate(0 ${ART.sideDy})` }));
  s.append(el('path', { d, fill: color, ...stroke(color), class: 'gm-face' }));
  const tri = round === 13;
  s.append(el('path', {
    d, fill: 'none', stroke: '#fff', 'stroke-opacity': '.42', 'stroke-width': '2.2', 'stroke-linejoin': 'round',
    transform: tri ? 'translate(50 58.7) scale(0.97) translate(-50 -58.7)' : 'translate(50 47) scale(0.86) translate(-50 -47)',
  }));
}

function gloss(s, d) {
  if (d) s.append(el('path', { d, fill: 'none', stroke: '#fff', 'stroke-opacity': '.6', 'stroke-width': '4', 'stroke-linecap': 'round' }));
}

// The face of a dot as an <svg> (suit piece with its number, or the Spark).
export function faceSvg(dot) {
  const s = svg();
  if (dot.s) {
    const sp = ART.spark;
    body(s, sp.path, 0, sp.color, sp.side);
    s.append(el('path', { d: sp.starPath, fill: sp.star, stroke: ART.plate, 'stroke-width': '3.5', 'stroke-linejoin': 'round', 'paint-order': 'stroke', class: 'gm-star' }));
    s.append(el('path', { d: sp.core, fill: '#fff3d6', opacity: '.85' }));
    gloss(s, 'M20 30A36 36 0 0 1 40 12');
    return s;
  }
  const su = ART.suits[dot.c];
  if (!su) return s;
  body(s, su.path, su.round, su.color, su.side);
  gloss(s, su.gloss);
  const two = dot.n >= 10;
  const txt = el('text', {
    x: su.number.x, y: su.number.y, 'font-size': two ? su.number.size2 : su.number.size, 'text-anchor': 'middle',
    fill: ART.plate, 'font-weight': 800, 'font-stretch': '75%', 'letter-spacing': '-1.5', class: 'gm-num',
  });
  txt.textContent = String(dot.n);
  s.append(txt);
  return s;
}

// The back of a Stack dot: a dark felt piece with the site's mark (two points and the pass between them).
export function backSvg() {
  const s = svg();
  body(s, ART.spark.path, 0, '#1d3a2d', '#0a1712');
  s.append(el('circle', { cx: 32, cy: 60, r: 9, fill: '#ff7a3d' }));
  s.append(el('circle', { cx: 68, cy: 34, r: 7, fill: '#f4efe3' }));
  s.append(el('path', { d: 'M39 53Q46 32 61 35', fill: 'none', stroke: '#f4efe3', 'stroke-width': 4, 'stroke-dasharray': '6 6', 'stroke-linecap': 'round', opacity: '.8' }));
  return s;
}

// The spoken name of a dot ("Coral 7" / "7 coral"). Literal keys, one per suit (tests/test_i18n.py).
export function dotName(dot) {
  if (!dot) return '';
  if (dot.s) return dot.as ? t('family.games.play.dot.spark_as', { dot: dotName(dot.as) }) : t('family.games.play.dot.spark');
  switch (dot.c) {
    case 'r': return t('family.games.play.dot.r', { n: dot.n });
    case 'b': return t('family.games.play.dot.b', { n: dot.n });
    case 'g': return t('family.games.play.dot.g', { n: dot.n });
    case 'p': return t('family.games.play.dot.p', { n: dot.n });
    default: return '';
  }
}

// A whole piece. opts: {tag:'span'|'button', cls, label, onclick, back:true (face down), attrs}
export function dotNode(dot, opts = {}) {
  const node = document.createElement(opts.tag || 'span');
  const k = !dot || opts.back ? 'x' : dot.s ? 's' : dot.c;
  node.className = 'gm-dot gm-dot--' + k + ' gp-dot' + (dot && dot.s && dot.as && !opts.back ? ' gm-dot--as' : '') + (opts.cls ? ' ' + opts.cls : '');
  if (opts.tag === 'button') node.type = 'button';
  const label = opts.label != null ? opts.label : opts.back ? '' : dotName(dot);
  if (label) node.setAttribute('aria-label', label);
  else node.setAttribute('aria-hidden', 'true');
  for (const [a, v] of Object.entries(opts.attrs || {})) if (v != null && v !== false) node.setAttribute(a, v === true ? '' : String(v));
  if (opts.onclick) node.addEventListener('click', opts.onclick);
  node.append(opts.back || !dot ? backSvg() : faceSvg(dot));
  if (dot && dot.s && dot.as && !opts.back) {
    const b = document.createElement('span');
    b.className = 'gm-as';
    b.setAttribute('aria-hidden', 'true');
    b.append(faceSvg(dot.as));
    node.append(b);
  }
  return node;
}
